apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      imagePullSecrets:
      - name: dockerhub-creds
      containers:
      - name: guestbook-ui
        image: docker.io/argoproj/guestbook-ui:v2
        ports:
        - containerPort: 3000

